version: '3.8'

services:
  stremio-trakt-addon:
    image: reddravenn/stremio-trakt-addon
    container_name: stremio-trakt-addon
    ports:
      - "7000:7000"
    environment:
      PORT: 7000
      BASE_URL: http://localhost:7000
      DB_USER: postgres_user
      DB_HOST: stremio_postgres
      DB_NAME: stremio_trakt_db
      DB_PORT: 5432
      DB_MAX_CONNECTIONS: 20
      DB_IDLE_TIMEOUT: 30000
      DB_CONNECTION_TIMEOUT: 2000
      REDIS_HOST: stremio_redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 
      TMDB_CACHE_DURATION: 1d
      TRAKT_CACHE_DURATION: 1d
      TRAKT_HISTORY_FETCH_INTERVAL: 1d
      LOG_LEVEL: info
      LOG_INTERVAL_DELETION: 3d
      NODE_ENV: production
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./cache:/usr/src/app/cache
      - ./log:/usr/src/app/log

  postgres:
    container_name: stremio_postgres
    image: postgres:16.4
    environment:
      POSTGRES_DB: stremio_trakt_db
      POSTGRES_USER: postgres_user
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d stremio_trakt_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    container_name: stremio_redis
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
